language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx-2
env:
  - POSTGIS=2.0
gemfile:
  - travis/ar40.gemfile
allow_failures:
  - rbx-2
matrix:
  exclude:
before_install: ./travis/before_install.sh
before_script: ./travis/before_script.sh
script: bundle exec rake test
