language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-2
env:
  - POSTGIS=2.0
gemfile:
  - travis/ar40.gemfile
  - travis/ar41.gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
before_install: ./travis/before_install.sh
before_script: ./travis/before_script.sh
script: bundle exec rake test
