language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
#  - rbx-19mode
env:
  - POSTGIS=1.5
  - POSTGIS=2.0
gemfile:
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
before_install: ./bin/ci/before_install.sh
before_script: ./bin/ci/before_script.sh
script: bundle exec rake test
