language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - jruby-9.2.6.0
gemfile:
  - gemfiles/ar60.gemfile
matrix:
  # additional tests for different postgresql/postgis versions
  # only testing against the latest ruby version for these
  include:
    - rvm: 2.7
      addons:
        postgresql: 9.6
        apt:
          packages:
            - postgresql-9.6-postgis-2.4
    - rvm: 2.7
      addons:
        postgresql: 11
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
            - postgresql-11-postgis-3
            - postgresql-11-postgis-3-scripts
      env:
        - PGPORT=5433
      before_install:
        - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/11/main/pg_hba.conf
        - sudo pg_ctlcluster 11 main restart
    - rvm: 2.7
      addons:
        postgresql: 12
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-12-postgis-3
            - postgresql-12-postgis-3-scripts
      env:
        - PGPORT=5433
      before_install:
        - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
        - sudo pg_ctlcluster 12 main restart
  allow_failures:
    - rvm: jruby-9.2.6.0
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
env:
  global:
    - PGPORT=5432
services:
  - postgresql
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
